#ifndef __settingsdialog__
#define __settingsdialog__

#include <wx/fileconf.h>
#include <string>
#include <map>
/**
@file
Subclass of SettingsDialogGui, which is generated by wxFormBuilder.
*/

#include "gui.h"
#include "inifileext.h"
//// end generated include

/** Implementing SettingsDialogGui */
class SettingsDialog : public SettingsDialogGui
{
public:
	SettingsDialog(wxWindow* parent, const std::string& iniPath);

	bool AlwaysShow() const { return chkAlwaysShow->IsChecked(); }

private:
	IniFileExt mConfig;
	std::map<wxString, std::function<void(SettingsDialog*, wxWindow*)>> mSavers, mLoaders;

	void loadChildren(wxWindow* parent);
	void saveChildren(wxWindow* parent);
	void loadControl(wxWindow* ctrl);
	void saveControl(wxWindow* ctrl);

	void saveCheckBox(wxWindow* chkBox);
	void saveChoice(wxWindow* cbChoice);
	void loadCheckBox(wxWindow* chkBox);
	void loadChoice(wxWindow* cbChoice);

protected:
	virtual void btnOK_Click(wxCommandEvent& event);
};

#endif // __settingsdialog__
