#ifndef __settingsdialog__
#define __settingsdialog__

#include <wx/fileconf.h>
#include <string>
/**
@file
Subclass of SettingsDialogGui, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing SettingsDialogGui */
class SettingsDialog : public SettingsDialogGui
{
public:
		/** Constructor */
		SettingsDialog(wxWindow* parent, const std::string& iniPath);
	//// end generated class members

private:
	wxFileConfig mConfig;

	void setDialogItemFromConfig(const wxFileConfig& config, const wxString& key, bool defValue, wxCheckBox* chkBox);
	void setDialogItemFromConfig(const wxFileConfig& config, const wxString& key, const wxString& defValues, 
								 const wxString& defValueKey, int defValueIndex, wxChoice* cbChoice);

protected:
	virtual void btnOK_Click(wxCommandEvent& event);
};

#endif // __settingsdialog__
