#ifndef __settingsdialog__
#define __settingsdialog__

/**
@file
Subclass of SettingsDialogGui, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing SettingsDialogGui */
class SettingsDialog : public SettingsDialogGui
{
	public:
		/** Constructor */
		SettingsDialog( wxWindow* parent );
	//// end generated class members


};

#endif // __settingsdialog__
